name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.1.0

      - name: Yarn install
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test-ci

      - name: Check Typescript types
        run: yarn check-types

      - name: Lint
        run: yarn lint-ci

      - name: Build Storybook
        run: yarn build-storybook

